"""Create initial tables.

Revision ID: 001_initial
Revises: 
Create Date: 2026-02-17 18:58:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Install pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # Create sessions table
    op.create_table(
        'sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create tasks table
    op.create_table(
        'tasks',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('original_task', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_steps', sa.Integer(), nullable=False),
        sa.Column('final_response', sa.JSON(), nullable=True),
        sa.Column('execution_summary', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_session_id', 'tasks', ['session_id'])
    
    # Create task_steps table
    op.create_table(
        'task_steps',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('step_number', sa.Integer(), nullable=False),
        sa.Column('step_type', sa.String(length=100), nullable=False),
        sa.Column('node_name', sa.String(length=255), nullable=False),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('output_data', sa.JSON(), nullable=True),
        sa.Column('model_used', sa.String(length=255), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_steps_task_id', 'task_steps', ['task_id'])
    
    # Create memory_vectors table with embedding column
    op.create_table(
        'memory_vectors',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', sa.String(), nullable=True),  # Will be updated to vector type
        sa.Column('memory_type', sa.String(length=100), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_vectors_session_id', 'memory_vectors', ['session_id'])
    
    # Update embedding column to use vector type (done via raw SQL)
    op.execute('ALTER TABLE memory_vectors ALTER COLUMN embedding TYPE vector(768) USING embedding::vector(768)')
    
    # Create HNSW index on embedding column
    op.execute('CREATE INDEX ix_memory_vectors_embedding ON memory_vectors USING hnsw (embedding vector_cosine_ops)')
    
    # Create audit_logs table
    op.create_table(
        'audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('component', sa.String(length=100), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_session_id', 'audit_logs', ['session_id'])
    op.create_index('ix_audit_logs_task_id', 'audit_logs', ['task_id'])
    
    # Create checkpoints table
    op.create_table(
        'checkpoints',
        sa.Column('thread_id', sa.String(length=255), nullable=False),
        sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
        sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
        sa.Column('parent_checkpoint_id', sa.String(length=255), nullable=True),
        sa.Column('checkpoint_data', sa.LargeBinary(), nullable=False),
        sa.Column('channel_values', sa.LargeBinary(), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoints')
    op.drop_index('ix_audit_logs_task_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_session_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_memory_vectors_embedding', table_name='memory_vectors')
    op.drop_index('ix_memory_vectors_session_id', table_name='memory_vectors')
    op.drop_table('memory_vectors')
    op.drop_index('ix_task_steps_task_id', table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index('ix_tasks_session_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('sessions')
    # ### end Alembic commands ###
